services:
  gonic:
    image: sentriz/gonic:latest
    restart: unless-stopped

    environment:
      TZ: Europe/Paris
      GONIC_HTTP_LOG: ${GONIC_HTTP_LOG:-false}
      GONIC_PROXY_PREFIX: ${GONIC_PROXY_PREFIX:-/}
      GONIC_SCAN_AT_START_ENABLED: ${GONIC_SCAN_AT_START_ENABLED:-true}
      GONIC_SCAN_WATCHER_ENABLED: ${GONIC_SCAN_WATCHER_ENABLED:-true}
      GONIC_MULTI_VALUE_GENRE: delim \,
      GONIC_MULTI_VALUE_ARTIST: multi
      GONIC_MULTI_VALUE_ALBUM_ARTIST: multi
      GONIC_JUKEBOX_ENABLED: ${GONIC_JUKEBOX_ENABLED:-true}
      GONIC_EXPVAR: ${GONIC_EXPVAR:-false}
    ports:
      - 11445:80
    volumes:
      - gonic-data:/data
      - gonic-cache:/cache
      - $MUSIC_BASE_PATH/library:/music:ro
      - $MUSIC_BASE_PATH/playlists:/playlists

  beets:
    image: linuxserver/beets:latest

    environment:
      TZ: Europe/Paris
      PUID: 1000
      PGID: 1000
    volumes:
      - beets-config:/config
      # See README.md on why this is commented. Use "beet config -e"
      - $MUSIC_BASE_PATH/library:/music
      - $MUSIC_BASE_PATH/ingest:/downloads
    ports:
      - 22654:8337

volumes:
  gonic-data:
  gonic-cache:
  beets-config:
